#! /bin/bash
echo "start building..."
env GOOS=linux GOARCH=amd64 go build -o "eduX-linux-amd64"
echo "1/6"
env GOOS=linux GOARCH=386 go build -o "eduX-linux-i386"
echo "2/6"
env GOOS=darwin GOARCH=amd64 go build -o "eduX-osx-amd64"
echo "3/6"
env GOOS=darwin GOARCH=386 go build -o "eduX-osx-i386"
echo "4/6"
env GOOS=windows GOARCH=amd64 go build -o "eduX-windows-amd64.exe"
echo "5/6"
env GOOS=windows GOARCH=386 go build -o "eduX-windows-i386.exe"
echo "6/6"
echo "build complete!"